### ISSUE TITLE
Install on Ubuntu 18.04

### ISSUE THREAD

**Issue by yvesdhalu** [dominiksalvet/asus-zenbook-ux430ua-linux#1]
File "/etc/rc.local" doesn't exists, so you need to add "#!/bin/bash" on the first line and set execute permission.

**Comment by dominiksalvet** [comment]
@yvesdhalu Thank you for your feedback, now it should be okay.

**Comment by dominiksalvet** [comment]
@yvesdhalu BTW, if you want to repair your installation manually, you can use the following *rc.local* file content:
```bash
#!/bin/sh -e

/usr/local/bin/jack-config # if you proceeded with option 1)
/usr/local/bin/fan-config # if you proceeded with option 2)
exit 0
```

But I guess, you already have done it.
